kind: Deployment
apiVersion: apps/v1
metadata:
  name: job-assignment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: container-html
        image: shahidjaber/job-assignment:v1
        imagePullPolicy: IfNotPresent
